# Global settings applied to the whole site.
[build]
  publish = "public"
    command = "hugo"

    [context.production.environment]
      HUGO_ENV = "production"

      [context.deploy-preview]
        command = "hugo --baseURL $DEPLOY_PRIME_URL"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/asb-calendar"
  to = "https://www.trumba.com/calendars/sau39-master.json?mixin=823099%2c823106%2c771757"
  status = 200
  force = true
